# Generated by Django 4.0 on 2022-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
