# Generated by Django 4.0.2 on 2022-03-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cnpj',
            new_name='cnpj_cpf',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_fantasia',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razao_social',
        ),
    ]
