# Generated by Django 4.0 on 2021-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendador', '0002_rename_razaosocial_empresa_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
    ]
